# Generated by Django 4.0.1 on 2023-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oregon_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.CharField(max_length=10)),
                ('numbers', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('draw_date',),
            },
        ),
    ]
