# Generated by Django 4.0.1 on 2023-03-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_numbers_app', '0003_rename_lottery_results_lotteryresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryresults',
            name='numbers',
            field=models.CharField(max_length=30),
        ),
    ]
